// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const PLACEHOLDER_URL = "https://placeholder.supabase.co";
const PLACEHOLDER_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

function readEnv(name: "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY"): string | undefined {
  const raw = import.meta.env[name];
  if (typeof raw !== "string") return undefined;
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

const configuredUrl = readEnv("VITE_SUPABASE_URL");
const configuredKey = readEnv("VITE_SUPABASE_PUBLISHABLE_KEY");

/** False when build omitted or blank Vite env vars — app still renders; data/auth won't work. */
export const isSupabaseConfigured = Boolean(configuredUrl && configuredKey);

const url = configuredUrl ?? PLACEHOLDER_URL;
const key = configuredKey ?? PLACEHOLDER_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

if (!isSupabaseConfigured && import.meta.env.PROD) {
  console.warn("[Lumen] Auth backend is not configured for this build.");
}
